### ISSUE TITLE
[User Story] As a systems engineer, I would like to know the network usage of processes on my remote device

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/ttg-healthcheck#10]
### **Is your user story related to a problem? Please describe.**
As a systems engineer, I am frustrated by the steps needed to retrieve a processes' network port and protocol information running on my remote rasberryPi.

### **Describe the solution you'd like**
I would like to see the network port and protocol information (if available) of all the processes running on my remote device  viewable in my database so that I may quickly refer and retrieve the information.

### **Describe alternatives you've considered**
Obtaining the information from a shell-only method is tedious and is not convenient.

### **Additional context**
The information can be sent to either SQL-style tables or as part of a MongoDB document.
Related to issue #1

**Comment by arich94** [comment]
Could not find command line arguments to get network by process -- went with overall network usage

**Comment by Pyxsys** [comment]
Issue is closed with #158.
