### ISSUE TITLE
[Acceptance Test] Sending Pi Information To The DB

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#124]
## **Description and Goal of Test**
The goal of this test is to demonstrate that the Raspberry Pi device can properly scrub the information from the Linux device it is running on and send the necessary information to the DB.

#### **Acceptance Criteria**
- [x] retrieves the CPU information from the device
- [x] the DB is updated with the device data

**Comment by Dewakar** [comment]
reviewed CPU transfer task with @Pyxsys 

Looks great! thank you!
