### ISSUE TITLE
[Acceptance Test] Signup and Login

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#137]
## **Description and Goal of Test**
A user can create a new account and enter the application with proper credentials

#### **Acceptance Criteria**
- [x] Create a new account with email and password
- [x] Login using email and password
- [x] Logout of account
- [x] Cannot create account with email already existing
- [x] Cannot login with improper email or password

**Comment by Dewakar** [comment]
Reviewed all login tasks mentioned above with @DerekRuiz  @shash3.

All good to go!
