### ISSUE TITLE
[Acceptance Test] Visualize Pi Devices in a Table

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#138]
## **Description and Goal of Test**
Display a list of Pi Devices in a table, and the information of a Pi Device after selecting one from the table.

#### **Acceptance Criteria**
- [x] Display Pi Devices in a table
- [x] Click a Pi Device to see its attributes
- [x] Apply filters to change the table of Pi Devices

**Comment by Dewakar** [comment]
Reviewed the devices table on the above mentioned tasks with @DerekRuiz  @shash3 

Great work! thanks guys!
