### ISSUE TITLE
[User Story] As a data analyst, I would like to know the memory usage of a specific device

### ISSUE THREAD

**Issue by arich94** [Pyxsys/ttg-healthcheck#15]
### **Is your user story related to a problem? Please describe.**
It frustrates me when I cannot easily discern the memory usage of a Raspberry Pi computer that my machines are relying on.

### **Describe the solution you'd like**
I'd like to be able to easily view the memory usage data as provided by the daemon.

### **Describe alternatives you've considered**
Manually seeking memory usage data is troublesome and difficult.

### **Additional context**
The memory usage data should include:
- Percentage of memory used (%)
- How much is currently in use (nB)
- How much is available (nB)
- How much is cached (nB)
- ~~Paged pool (nB)~~
- ~~Non-paged pool (nB)~~

**Comment by Pyxsys** [comment]
Paged pools are a feature of Windows OS, thus cannot be obtained on UNIX-based operating systems.
They have been removed as a requirement as it violates  Issue #13

[This can be used](https://unix.stackexchange.com/questions/531554/are-linux-kernel-modules-a-sort-of-linux-system-paged-pool) to get a better understanding of the differences.
