### ISSUE TITLE
[Developer Story] As a developer, I want the database to store the process information in an easy to retrieve structure

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#156]
### **Is your user story related to a problem? Please describe.**
The database should store the processes information so that the least amount of queries are required to load a page and return all useful information.

### **Describe the solution you'd like**
Change the storage structure of the database to use a single collection for the process information rather than separate the information in the database. This will allow for retrieval of all process information in a more timely fashion as well as better organization of the processes data.

### **Describe alternatives you've considered**
Separating the data before saving it to the database was considered, then to retrieve only the desired categories (CPU, memory, etc.). This was initially chosen so that we could request specific information without filling the network with unnecessary data retrieval. 

This was not chosen however, due to the fact that most of the queries were for all the process categories (CPU, memory, etc.) at the same time, so many queries were being used anyways. In addition, the process categories should be synchronous with each other, therefore separating them is not necessary.

**Comment by Pyxsys** [comment]
Updating story points to better reflect needed effort.

All Models are getting changed.
All APIs are consequently getting changed.
Tests need to be updated accordingly.

![image.png](https://images.zenhubusercontent.com/61356fe96eed5f01f1f4ed1f/16ba98fc-010b-4a89-909b-00fbeb1784e0)

**Comment by Pyxsys** [comment]
Need models to be static and daemon.test.js tests to pass before adding Disk Info insertion from daemon. Issue is currently blocking #18 #17
