### ISSUE TITLE
[User Story] As a systems engineer, I would like to know the disk specifications of a specific device

### ISSUE THREAD

**Issue by arich94** [Pyxsys/ttg-healthcheck#18]
### **Is your user story related to a problem? Please describe.**
As a systems engineer, I am frustrated by not knowing the Disk specifications of the device I am monitoring.

### **Describe the solution you'd like**
I would like to see Disk specifications in my data and displayed on the application so I can easily associate Disk usage with the device I am monitoring.

### **Describe alternatives you've considered**
Obtaining the information from a command line or shell-only method is tedious and not convenient.

### **Additional context**
The information can be sent to either SQL-style tables or a MongoDB collection.
The disk specifications should include:
- Capacity (nB)
- Type (SSD, HDD, etc.)

**Comment by Pyxsys** [comment]
psutil does not contain functionality to list media type of connected hard disk. bodge involving terminal commands necessary and research into such adding to effort.
