### ISSUE TITLE
[Acceptance Test] Devices Table

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#192]
## **Description and Goal of Test**
To be able to access and view all the information on the devices table page.

#### **Acceptance Criteria**
- [x] View multiple devices in the table
- [x] Can sort the table by one of the criteria
- [x] Can filter the table by the device ID
- [x] Can link to more details on the device

**Comment by DerekRuiz** [comment]
If any portion is not fulfilled or if more information is requested on any section, please let us know.

**Comment by Dewakar** [comment]
- I can see multiple devices in the table
- Detail of device tables adjust dynamically as window size change
- sorting by different criteria works well
- filtering by device ID is functional
- device ID links to device detail page
