### ISSUE TITLE
[User Story] As a systems engineer, I would like to know the Wi-Fi specifications of a specific device

### ISSUE THREAD

**Issue by arich94** [Pyxsys/ttg-healthcheck#20]
### **Is your user story related to a problem? Please describe.**
As a systems engineer, I am frustrated by not knowing the Wi-Fi specifications of the device I am monitoring.

### **Describe the solution you'd like**
I would like to see Wi-Fi specifications in my data and displayed on the application so I can easily associate Wi-Fi usage with the device I am monitoring.

### **Describe alternatives you've considered**
Obtaining the information from a command line or shell-only method is tedious and not convenient.

### **Additional context**
The information can be sent to either SQL-style tables or a MongoDB collection.
The wi-fi specifications should include:
- Adapter name
- SSID
- Connection type
- IPv4 address
- IPv6 address

**Comment by Pyxsys** [comment]
Adapter name is a variable and holds no standard across OS'.
Solution needs to have user state which network adapter to monitor.

Solution will have OS default adapter names if given name is not found.
