### ISSUE TITLE
[User Story] As a data analyst, I would like to know the Wi-Fi usage of a specific device

### ISSUE THREAD

**Issue by arich94** [Pyxsys/ttg-healthcheck#21]
### **Is your user story related to a problem? Please describe.**
It frustrates me when I cannot easily discern the wi-fi usage of a Raspberry Pi computer that my machines are relying on.

### **Describe the solution you'd like**
I'd like to be able to easily view the wi-fi usage data as provided by the daemon.

### **Describe alternatives you've considered**
Manually seeking wi-fi usage data is troublesome and difficult.

### **Additional context**
The wi-fi usage data should include:
- send speed (Kbps)
- Receive speed (Kbps)
- Signal strength (hi, med, low)

**Comment by Pyxsys** [comment]
Partial implementation included with #158 (send/receive speed)
