### ISSUE TITLE
[Bug] Css opacity not working for deployed application

### ISSUE THREAD

**Issue by sachaelkaim** [Pyxsys/ttg-healthcheck#212]
### **Describe the bug**
All CSS opacity changes in CSS is not working on deployed application.

### **To Reproduce**
1. Go to 'https://pi-healthcheck.herokuapp.com/'
2. Login the application
3. Open navigation bar
4. Background opacity  when opening navigation is not working

### **Expected behavior**
Changes to opacity should work on deployed application.

### **Screenshots**
See image below of running application deployed vs locally

![22.png](https://images.zenhubusercontent.com/6137e2e5d762bdfc01a564cc/0d550a7a-5ce1-4560-866f-74248af7d374)

**Comment by arich94** [comment]
Current fix is on "profile-page" branch. Awaiting PR for fix to be marked as resolved.
