### ISSUE TITLE
[BUG] Invalid Conversion From String to Number (Wifi Signal Strength)

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#216]
### **Describe the bug**
Saving Wifi Signal Strength from daemon to the database causes the following error:
```wifi.signalStrength: Cast to Number failed for value "Strong" (type string) at path "signalStrength"```

### **To Reproduce**
1. Deploy the daemon on a PiOS x64 environment
2. Start the daemon using celebid -s
3. Wait 30s
4. Open the daemon log
5. See error

### **Expected behavior**
The wifi signal strength should be saved consistently with the database schemas.

### **Device (please complete the following information):**
 - type: Raspberry Pi
 - model: Raspberry Pi 3 Model B Plus Rev 1.3
 - OS: Debian GNU/Linux 11 (bullseye)
 - version: 11

### **Suggested fix**
Change the database schema to match the daemon report, or modify the daemon report to match the database schema.

**Comment by Pyxsys** [comment]
The regularly skipped tests  in the daemon also fail due to this issue when they are not skipped.

**Comment by Pyxsys** [comment]
Bug introduced with commit 0a5cb490486594a3f97beca0e51b8e82c19bd6a9
PR: #200
