### ISSUE TITLE
[Acceptance Test] Edit Users Profile Page

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#220]
## **Description and Goal of Test**
View and edit a user's profile page as a User or an Admin.

#### **Acceptance Criteria**
- [x] An admin can see a list of users/admin
- [x] An admin can edit input for a user/admin
- [x] An admin can delete any user/admin
- [x] A user can only see their profile
- [x] A user can edit their profile except for their role
- [x] Can see a log of user activities

**Comment by Dewakar** [comment]
- the tasks on this issue were completed and tested
