### ISSUE TITLE
[Acceptance Test] Analytics

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#228]
## **Description and Goal of Test**
To view and use the Analytics page.

#### **Acceptance Criteria**
- [x] Can see a list of top use CPU
- [x] Can see a list of top use Memory
- [x] Can set a threshold for each list

Can see a graph of historical data: 
- [x] For different devices
- [x] For a given attribute
- [x] For a time period
- [x] Export as CSV

**Comment by Dewakar** [comment]
- the tasks mentioned in this issue are completed
