### ISSUE TITLE
[Acceptance Test] Export CSV

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#229]
## **Description and Goal of Test**
Be able to export different tables to CSV format

#### **Acceptance Criteria**
- [x] Can export the log to a CSV
- [x] Can export the devices table to a CSV
- [x] Can export a device details to a CSV
- [x] Can export device processes to a CSV
- [x] Can export the devices that are only filtered out

**Comment by Dewakar** [comment]
- all the tasks in this issue have been completed
