### ISSUE TITLE
[User Story] As a systems engineer, I want the Daemon to shut down and restart if it uses more than 10% CPU or 1Mb memory

### ISSUE THREAD

**Issue by arich94** [Pyxsys/ttg-healthcheck#30]
### **Is your user story related to a problem? Please describe.**
It frustrates me when a background process uses too much CPU or memory and does not fix itself.

### **Describe the solution you'd like**
The daemon should restart should either of these conditions be met.

### **Describe alternatives you've considered**
Restarting is the most effective way to fix CPU and memory usage issues.

### **Additional context**
The daemon does not need both CPU and Memory usage issues to restart. I should restart when it encounters one or the other.

**Comment by Pyxsys** [comment]
Solution should not be bound to 10% CPU usage or 1Mb Memory usage. bounds should be configurable to prevent  unnecessary terminations on weaker hardware.
