### ISSUE TITLE
[User Story] As a system engineer, I want the API to communicate easily with both the database and the web application

### ISSUE THREAD

**Issue by arich94** [Pyxsys/ttg-healthcheck#31]
### **Is your user story related to a problem? Please describe.**
It frustrates me when the API does not communicate with all systems that it needs in order to complete its task.

### **Describe the solution you'd like**
The API should be configured such that it can communicate easily with both the database and the web application. This will ensure the information from the database can easily reach the web application.

### **Describe alternatives you've considered**
No other alternative should be considered. The API needs to perform its job properly.

### **Additional context**
No further context necessary.

**Comment by shash3** [comment]
PR #133 handles this issue on the server side.
