### ISSUE TITLE
[User Story] As a data analyst, I want to be able to analyze performance data of various systems in the Database. This would allow for conclusions on system health to be calculated and sent to the Web Application.

### ISSUE THREAD

**Issue by rex884** [Pyxsys/ttg-healthcheck#37]
### **Is your user story related to a problem? Please describe.**
It frustrates me when I have to manually analyze the performance data of various systems in order to calculate the conclusions on system health.

### **Describe the solution you'd like**
I want the web app to be able to analyze the performance data of multiple systems in the database and calculate the conclusions on system health. 

### **Describe alternatives you've considered**
There is no suitable alternative to this.

### **Additional context**
After the conclusions on system health are calculated, they should be sent to the Web Application.

**Comment by arich94** [comment]
This issue has been satisfied by color coding the information of each metric that is recorded and shown to the user.
