### ISSUE TITLE
[User Story] As a data analyst, I want the API to be able to store and retrieve log information

### ISSUE THREAD

**Issue by arich94** [Pyxsys/ttg-healthcheck#45]
### **Is your user story related to a problem? Please describe.**
It frustrates me when I cannot see a history of summaries or activities surrounding a specific machine so that I can determine patterns in its functionality.

### **Describe the solution you'd like**
I want to be able to see a log of previous summaries and actions taken by myself and/or other users for a specific machine.

### **Describe alternatives you've considered**
Taken the notes manually or having the log stored in the database is not preferable, as one could make mistakes manually and it could be hard to access it directly from the database without the use of the API.

### **Additional context**
While this specifies machine-centric logs, logs can also be user-centric so that a user may observe their own history within the application

**Comment by DerekRuiz** [comment]
closed with PR #222
