### ISSUE TITLE
[User Story] As a system developer, I want the user to be able to use their mobile phone or tablet to access and interact with every functional component of the web application.

### ISSUE THREAD

**Issue by rex884** [Pyxsys/ttg-healthcheck#67]
### **Is your user story related to a problem? Please describe.**
I'm frustrated when I can't use my web application on my mobile phone or tablet.

### **Describe the solution you'd like**
I want my web application to be able to access every page and interact with every functional component through a mobile phone or tablet.

### **Describe alternatives you've considered**
There is no suitable alternative to this.

### **Additional context**
No further context is necessary.

**Comment by arich94** [comment]
Mobile functionality is continuous issue. All current features work, all future features should work as well.
